---
abstract: 'Tidy and validate code in many ways at once'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Test::Class::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Code-TidyAll
no_index:
  directory:
    - lib/Code/TidyAll/t
    - lib/Code/TidyAll/Test
  file:
    - lib/Code/TidyAll/Util.pm
requires:
  Capture::Tiny: 0.12
  Config::INI::Reader: 0
  Date::Format: 0
  Digest::SHA1: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 0
  File::Slurp: 0
  File::Temp: 0
  File::Zglob: 0
  Hash::MoreUtils: 0
  List::MoreUtils: 0
  List::Pairwise: 0
  Log::Any: 0
  Moo: 0.0091010
  Scalar::Util: 0
  Time::Duration::Parse: 0
  Try::Tiny: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Code-TidyAll
  repository: git://github.com/jonswar/perl-code-tidyall.git
version: 0.04
