---
abstract: 'Engine for tidyall, your all-in-one code tidier and validator'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Encode: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Which: '0'
  Test::Class::Most: '0'
  Test::Differences: '0'
  Test::More: '0.88'
  Test::Warnings: '0'
  autodie: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.024, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Code-TidyAll
no_index:
  file:
    - lib/Code/TidyAll/Util.pm
provides:
  Code::TidyAll:
    file: lib/Code/TidyAll.pm
    version: '0.24'
  Code::TidyAll::Cache:
    file: lib/Code/TidyAll/Cache.pm
    version: '0.24'
  Code::TidyAll::Config::INI::Reader:
    file: lib/Code/TidyAll/Config/INI/Reader.pm
    version: '0.24'
  Code::TidyAll::Git::Precommit:
    file: lib/Code/TidyAll/Git/Precommit.pm
    version: '0.24'
  Code::TidyAll::Git::Prereceive:
    file: lib/Code/TidyAll/Git/Prereceive.pm
    version: '0.24'
  Code::TidyAll::Git::Util:
    file: lib/Code/TidyAll/Git/Util.pm
    version: '0.24'
  Code::TidyAll::Plugin:
    file: lib/Code/TidyAll/Plugin.pm
    version: '0.24'
  Code::TidyAll::Plugin::CSSUnminifier:
    file: lib/Code/TidyAll/Plugin/CSSUnminifier.pm
    version: '0.24'
  Code::TidyAll::Plugin::JSBeautify:
    file: lib/Code/TidyAll/Plugin/JSBeautify.pm
    version: '0.24'
  Code::TidyAll::Plugin::JSHint:
    file: lib/Code/TidyAll/Plugin/JSHint.pm
    version: '0.24'
  Code::TidyAll::Plugin::JSLint:
    file: lib/Code/TidyAll/Plugin/JSLint.pm
    version: '0.24'
  Code::TidyAll::Plugin::JSON:
    file: lib/Code/TidyAll/Plugin/JSON.pm
    version: '0.24'
  Code::TidyAll::Plugin::MasonTidy:
    file: lib/Code/TidyAll/Plugin/MasonTidy.pm
    version: '0.24'
  Code::TidyAll::Plugin::PHPCodeSniffer:
    file: lib/Code/TidyAll/Plugin/PHPCodeSniffer.pm
    version: '0.24'
  Code::TidyAll::Plugin::PerlCritic:
    file: lib/Code/TidyAll/Plugin/PerlCritic.pm
    version: '0.24'
  Code::TidyAll::Plugin::PerlTidy:
    file: lib/Code/TidyAll/Plugin/PerlTidy.pm
    version: '0.24'
  Code::TidyAll::Plugin::PodChecker:
    file: lib/Code/TidyAll/Plugin/PodChecker.pm
    version: '0.24'
  Code::TidyAll::Plugin::PodSpell:
    file: lib/Code/TidyAll/Plugin/PodSpell.pm
    version: '0.24'
  Code::TidyAll::Plugin::PodTidy:
    file: lib/Code/TidyAll/Plugin/PodTidy.pm
    version: '0.24'
  Code::TidyAll::Plugin::SortLines:
    file: lib/Code/TidyAll/Plugin/SortLines.pm
    version: '0.24'
  Code::TidyAll::Result:
    file: lib/Code/TidyAll/Result.pm
    version: '0.24'
  Code::TidyAll::SVN::Precommit:
    file: lib/Code/TidyAll/SVN/Precommit.pm
    version: '0.24'
  Code::TidyAll::SVN::Util:
    file: lib/Code/TidyAll/SVN/Util.pm
    version: '0.24'
  Code::TidyAll::Util::Zglob:
    file: lib/Code/TidyAll/Util/Zglob.pm
    version: '0.24'
  Test::Code::TidyAll:
    file: lib/Test/Code/TidyAll.pm
    version: '0.24'
requires:
  Capture::Tiny: '0'
  Config::INI::Reader: '0'
  Cwd: '0'
  Data::Dumper: '0'
  Date::Format: '0'
  Digest::SHA1: '0'
  Exporter: '0'
  File::Basename: '0'
  File::Find: '0'
  File::Path: '0'
  File::Slurp::Tiny: '0'
  File::Spec::Functions: '0'
  File::Temp: '0'
  File::Zglob: '0'
  Getopt::Long: '0'
  Guard: '0'
  IPC::Run3: '0'
  IPC::System::Simple: '0'
  List::MoreUtils: '0'
  Log::Any: '0'
  Moo: '0'
  Scalar::Util: '0'
  Test::Builder: '0'
  Text::ParseWords: '0'
  Time::Duration::Parse: '0'
  Try::Tiny: '0'
  base: '0'
  constant: '0'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Code-TidyAll
  homepage: http://metacpan.org/release/Code-TidyAll
  repository: git://github.com/autarch-code/perl-code-tidyall.git
version: '0.24'
x_Dist_Zilla:
  perl:
    version: '5.016003'
  plugins:
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@DROLSKY/MakeMaker'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@DROLSKY/Authority'
      version: '1.009'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@DROLSKY/AutoPrereqs'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@DROLSKY/CopyFilesFromBuild'
      version: '0.103510'
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename:
            - README.md
            - cpanfile
            - LICENSE
          exclude_match: []
          follow_symlinks: '0'
          include_dotfiles: '0'
          prefix: ''
          prune_directory: []
          root: .
      name: '@DROLSKY/GatherDir'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@DROLSKY/GitHub::Meta'
      version: '0.38'
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@DROLSKY/GitHub::Update'
      version: '0.38'
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@DROLSKY/MetaResources'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@DROLSKY/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.024'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@DROLSKY/MetaProvides::Package'
      version: '2.001002'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@DROLSKY/NextRelease'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@DROLSKY/PkgVersion'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@DROLSKY/TestMoreDoneTesting'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: '1'
          check_all_prereqs: '1'
          modules: []
          phase: release
          skip:
            - Dist::Zilla::Plugin::DROLSKY::Contributors
            - Dist::Zilla::Plugin::DROLSKY::License
      name: '@DROLSKY/stale modules, release'
      version: '0.028'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@DROLSKY/ReadmeMarkdownInBuild'
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@DROLSKY/ReadmeMarkdownInRoot'
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@DROLSKY/Test::PodSpelling'
      version: '2.006008'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@DROLSKY/Test::ReportPrereqs'
      version: '0.019'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@DROLSKY/PruneCruft'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@DROLSKY/ManifestSkip'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@DROLSKY/MetaYAML'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::License
      name: '@DROLSKY/License'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@DROLSKY/ExtraTests'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@DROLSKY/ExecDir'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@DROLSKY/ShareDir'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@DROLSKY/Manifest'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@DROLSKY/TestRelease'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@DROLSKY/ConfirmRelease'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@DROLSKY/UploadToCPAN'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@DROLSKY/CheckPrereqsIndexed'
      version: '0.012'
    -
      class: Dist::Zilla::Plugin::CPANFile
      name: '@DROLSKY/CPANFile'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::DROLSKY::Contributors
      name: '@DROLSKY/DROLSKY::Contributors'
      version: '0.24'
    -
      class: Dist::Zilla::Plugin::DROLSKY::License
      name: '@DROLSKY/DROLSKY::License'
      version: '0.24'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      config:
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@DROLSKY/Git::CheckFor::CorrectBranch'
      version: '0.011'
    -
      class: Dist::Zilla::Plugin::Git::Contributors
      config:
        Dist::Zilla::Plugin::Git::Contributors:
          include_authors: '0'
          include_releaser: '1'
          order_by: name
          paths: []
      name: '@DROLSKY/Git::Contributors'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@DROLSKY/Git::Describe'
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@DROLSKY/InstallGuide'
      version: '1.200005'
    -
      class: Dist::Zilla::Plugin::Meta::Contributors
      name: '@DROLSKY/Meta::Contributors'
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@DROLSKY/MetaConfig'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@DROLSKY/MetaJSON'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::SurgicalPodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: NAME
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.006'
            -
              class: inc::Pod::Weaver::Section::SeeAlsoCodeTidyAll
              name: =inc::Pod::Weaver::Section::SeeAlsoCodeTidyAll
              version: ~
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.006'
            -
              class: Pod::Weaver::Section::Contributors
              name: Contributors
              version: '0.008'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.006'
      name: '@DROLSKY/SurgicalPodWeaver'
      version: '0.0021'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@DROLSKY/PodSyntaxTests'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@DROLSKY/Test::CPAN::Changes'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
      name: '@DROLSKY/Test::EOL'
      version: '0.15'
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/author/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: '@DROLSKY/Test::NoTabs'
      version: '0.09'
    -
      class: Dist::Zilla::Plugin::Test::Pod::No404s
      name: '@DROLSKY/Test::Pod::No404s'
      version: '1.001'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - cpanfile
            - CONTRIBUTING.md
            - LICENSE
            - README.md
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@DROLSKY/Git::Check'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - cpanfile
            - CONTRIBUTING.md
            - LICENSE
            - README.md
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@DROLSKY/Git::Commit'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: v0.24
          tag_format: v%v
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@DROLSKY/Git::Tag'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@DROLSKY/Git::Push'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: DevelopRequires
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.024'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@DROLSKY/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.024'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.024'
x_authority: cpan:DROLSKY
x_contributors:
  - 'George Hartzell <georgewh@gene.com>'
  - 'Gregory Oschwald <goschwald@maxmind.com>'
  - 'Joe Crotty <joe.crotty@returnpath.net>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
  - 'Pedro Melo <melo@simplicidade.org>'
