
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
DROLSKY
DROLSKY's
Rolsky
Rolsky's
API
CPAN
JSON
JavaScript
Misc
PHP
PREREQS
Raggett
STDERR
STDIN
STDOUT
Simakov
TIDYALL
Thalhammer
Vim
argv
ascii
atomicity
cmd
conf
config
cssunminifier
ctrl
dir
filename
iff
ispell
js
jsbeautify
jshint
jslint
lib
listref
masontidy
noll
npm
ok
ops
params
pathname
perlcritic
perlcriticrc
perltidy
phpcs
plugins
podspell
podtidy
pre
prereqs
repo
repos
runtime
sourceforge
svn
tidiers
tidyall
timestamped
ttl
txn
validator
validators
Jonathan
Swartz
swartz
Dave
autarch
George
Hartzell
georgewh
Gregory
Oschwald
goschwald
Joe
Crotty
joe
Olaf
Alders
olaf
Pedro
Melo
melo
Code
TidyAll
Plugin
PerlTidy
JSBeautify
JSLint
Git
Prereceive
MasonTidy
SVN
Precommit
Config
INI
Reader
Result
Util
Zglob
Cache
PerlCritic
PodChecker
Test
JSHint
CSSUnminifier
PodSpell
PHPCodeSniffer
PodTidy
SortLines
